Repository danishzayan/StudentsShowcase, pull requests merged in 2023-10, with the labels that each got.

#6 Added New Student Profile
  script.js
Labels: hacktoberfest-accepted

#10 new student added
  profileData.js
Labels: hacktoberfest-accepted

#11 Added new profile
  profileData.js
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#13 Added myself in contributers
  profileData.js
Labels: hacktoberfest-accepted

#16 Add files via upload
  profileData.js
Labels: hacktoberfest-accepted

#17 Display 'Message' button only if a mail is available
  profileData.js
  script.js
Labels: hacktoberfest-accepted

#19 hparihar-07 profileData.js added
  profileData.js
Labels: hacktoberfest-accepted

#20 add new student
  profileData.js
Labels: hacktoberfest-accepted

#22 I have added my data
  profileData.js
Labels: hacktoberfest-accepted

#23 changes
  profileData.js
Labels: hacktoberfest, hacktoberfest-accepted

#24 Add user information
  profileData.js
Labels: hacktoberfest-accepted

#26 Updated profileData.js
  profileData.js
Labels: hacktoberfest-accepted

#25 Add my profile
  profileData.js
Labels: hacktoberfest-accepted

#29 Add a new profile
  profileData.js
Labels: hacktoberfest-accepted

#28 Fixed the bug that there is extra comma showing in the skills section
  profileData.js
  script.js
Labels: hacktoberfest-accepted
